### ISSUE TITLE
create continuous view query with multiple statements breaks the worker

### ISSUE THREAD

**Issue by loadzero** [pipelinedb/pipelinedb#1075]
simple_query_exec can take multiple statements in the query string. 

It looks like this gets sucked into view->query and kills the worker, which is only expecting one statement.

```py
#!/usr/bin/env python

import psycopg2
import time
import sys

def main():
	cs = "postgres://:6543?host=/tmp"
	con = psycopg2.connect(cs)
	cur = con.cursor()

	foo = cur.execute("create continuous view v_adhoc as select x::int, count(*) from stream group by x; select('hello');")

	con.commit()

	foo2 = cur.execute("insert into stream(x) values(1);")
	con.commit()
	
if __name__ == "__main__":
	main()
```

```
#0  0x00002b74b2b00cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00002b74b2b040d8 in __GI_abort () at abort.c:89
#2  0x000000000092a60f in ExceptionalCondition (conditionName=0xab8dc8 "!(list_length(parsetree_list) == 1)", errorType=0xab8d6f "FailedAssertion", fileName=0xab8c80 "cont_plan.c", lineNumber=417) at assert.c:65
#3  0x000000000073ec6a in get_worker_plan (view=0x2651538) at cont_plan.c:417
#4  0x000000000073edd7 in GetContPlan (view=0x2651538) at cont_plan.c:464
#5  0x000000000074bdf7 in init_query_state (state=0x264fa68, id=1, context=0x253ace0, owner=0x253adf8, reader=0x253b140) at cont_worker.c:110
#6  0x000000000074c1c5 in get_query_state (states=0x264d528, id=1, context=0x253ace0, owner=0x253adf8, reader=0x253b140) at cont_worker.c:213
#7  0x000000000074c6c8 in ContinuousQueryWorkerMain () at cont_worker.c:361
#8  0x000000000074ab81 in cq_bgproc_main (arg=47780453876384) at cont_scheduler.c:409
#9  0x0000000000758c08 in StartBackgroundWorker () at bgworker.c:746
#10 0x000000000076c2b3 in do_start_bgworker (rw=0x255a210) at postmaster.c:5522
#11 0x000000000076c5cf in maybe_start_bgworker () at postmaster.c:5706
#12 0x00000000007671e6 in ServerLoop () at postmaster.c:1689
#13 0x0000000000766644 in PostmasterMain (argc=7, argv=0x2538fc0) at postmaster.c:1261
#14 0x00000000006a9bff in main (argc=7, argv=0x2538fc0) at main.c:229
```

**Comment by usmanm** [comment]
This should be fixed by #1032.
