### ISSUE TITLE
ERROR: unrecognized node type: 960

### ISSUE THREAD

**Issue by gb198871** [pipelinedb/pipelinedb#1891]
use java JDBC exec : 
jdbc:postgresql://" + ip + ":" + port + "/" + dbname
stmt = connection.createStatement();
stmt.executeUpdate("CREATE CONTINUOUS TRANSFORM t_random_ggd AS SELECT (post_data->>'a')::text as a FROM random_ggd THEN EXECUTE PROCEDURE pipeline_stream_insert('ggd')");

org.postgresql.util.PSQLException: ERROR: unrecognized node type: 960
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:305) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:291) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:249) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228) ~[commons-dbcp-1.3.jar:1.3]
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228) ~[commons-dbcp-1.3.jar:1.3]

but exec create stream is ok.

**Comment by derekjn** [comment]
@gb198871 can you share the output of `SELECT pipeline_version()`?

**Comment by gb198871** [comment]
pipeline_version
------------------------------------------------------------------------------------------------------------------
 PipelineDB  at revision  on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit

**Comment by nankingrider** [comment]
Hi, this is because your client is not working under SIMPLE mode, so the client compiles the sql string then send it to pipelinedb, in this case, pipelinedb will not recognize some types. 
solution: add following prop in your jdbc param.
props.setProperty("preferQueryMode", "simple");

**Comment by nankingrider** [comment]
@gb198871 @derekjn
