### ISSUE TITLE
WARNING:  TupleDesc reference leak: TupleDesc

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1936]
version:0.9.8

bt:
```
(gdb) bt
#0  PrintTupleDescLeakWarning (tupdesc=0x7f456e3e1740) at resowner.c:1087
#1  0x000000000099e86a in ResourceOwnerReleaseInternal (owner=0x1cff6a8, phase=RESOURCE_RELEASE_AFTER_LOCKS, isCommit=1 '\001', isTopLevel=1 '\001') at resowner.c:378
#2  0x000000000099e414 in ResourceOwnerRelease (owner=0x1cff6a8, phase=RESOURCE_RELEASE_AFTER_LOCKS, isCommit=1 '\001', isTopLevel=1 '\001') at resowner.c:212
#3  0x0000000000522cc5 in CommitTransaction () at xact.c:2094
#4  0x00000000005237af in CommitTransactionCommand () at xact.c:2744
#5  0x0000000000780eb8 in exec_commit (exec=0x1d50478) at executor.c:70
#6  0x00000000007818c1 in ContExecutorEndBatch (exec=0x1d50478, commit=1 '\001') at executor.c:428
#7  0x0000000000778bb0 in ContinuousQueryWorkerMain () at worker.c:409
#8  0x0000000000776ae5 in cont_bgworker_main (arg=139936030723808) at scheduler.c:398
#9  0x000000000078a8e6 in StartBackgroundWorker () at bgworker.c:730
#10 0x000000000079e119 in do_start_bgworker (rw=0x1c7e620) at postmaster.c:5585
#11 0x000000000079e3f0 in maybe_start_bgworker () at postmaster.c:5760
#12 0x00000000007991a1 in ServerLoop () at postmaster.c:1777
#13 0x00000000007985e5 in PostmasterMain (argc=3, argv=0x1c588c0) at postmaster.c:1310
#14 0x00000000006cb982 in main (argc=3, argv=0x1c588c0) at main.c:229
```

logfile:
```
401 WARNING:  TupleDesc reference leak: TupleDesc 0x7f456e3e1740 (32770,-1) still referenced
402 WARNING:  TupleDesc reference leak: TupleDesc 0x7f456e3e1740 (32770,-1) still referenced
403 WARNING:  TupleDesc reference leak: TupleDesc 0x7f456e3e1740 (32770,-1) still referenced
404 WARNING:  TupleDesc reference leak: TupleDesc 0x7f456e3e1740 (32770,-1) still referenced
```
![e4511bba-8f24-47b9-8b94-8fd845639d5b](https://user-images.githubusercontent.com/3765918/42608621-337936e2-85bb-11e8-99a9-9e3f696af5c8.png)

some CV use table ```iprobe_dev_tbl``` like:
```create continuous view v as select cols from stream,iprobe_dev_tbl where quals....```

**Comment by sangli00** [comment]
@derekjn  https://github.com/pipelinedb/pipelinedb/issues/1906   0.9.9 is fixed.
